### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
`mocha-sugar-free` is not compatible so we need a replacement.

**Comment by DanielRuf** [comment]
> The other comes from the Blob-slice.html test which appears to be affected by a change in the vm

Yes, seems so. At least the mentioned mocha package throws the error.
Ok, should I close this PR or wait until we got it fixed and then trigger a new build?

**Comment by Zirro** [comment]
We could probably keep this open if we intend to merge it later, but I'm not sure that we want to test in all three versions at the same time due to CI limits. @Domenic?

**Comment by DanielRuf** [comment]
Probably just 8 (LTS) and 10 (stable).

**Comment by domenic** [comment]
Ended up doing this as part of https://github.com/jsdom/jsdom/commit/1c792e1a1bf9f2ff842ccef749b01f95b60bd364 where we're moving the minimum version to v8.

**Pull request closed without merging**
