### PR TITLE
fix: added tooShort/tooLong validation support. 

### PR DESCRIPTION
**Pull request by 007tom**
Context: https://github.com/jsdom/jsdom/pull/2142#issuecomment-362946100

### CODE REVIEW

**Comment by domenic** [comment]
That does not address my comment.

**Comment by 007tom** [comment]
Thank you, my real question is how to test `tooShort` validity using jest if `tooShort` alwsys return `false`.

**Comment by 007tom** [comment]
So what's the problem of my commit, it works for me.

**Comment by domenic** [comment]
Your commit makes jsdom behave not like browsers behave, which is against our mission. You would realize this if you added tests (as is required by any PRs to this project), since those tests would not pass in browsers.

**Comment by 007tom** [comment]
That's also my concern, so it's in **Draft** state.

Whatever, maybe you're right!

Thank you!

**Pull request closed without merging**
