### PR TITLE
Fix location hash set empty behavior

### PR DESCRIPTION
**Pull request by matheusmb**
This PR fixes the issue described by #3494

### CODE REVIEW

**Comment by domenic** [comment]
Thanks! However we do not accept new tests in the to-port-to-wpts format. Can you add them in the WPT to-upstream format, per CONTRIBUTING.md?

**Comment by matheusmb** [comment]
Sure @domenic, I'll work on this tomorrow. I will take the opportunity and migrate this test suit to the new format. Thanks.

**Comment by matheusmb** [comment]
Hey @domenic, I took a look at the WPT tests and I could not find any case that would cover this behavior under [the location interface test cases](https://github.com/web-platform-tests/wpt/tree/master/html/browsers/history/the-location-interface). I'm wondering if this is a bug in browsers implementation 🤔. jsdom was implementing the hash setter according to the [URL Living Standard](https://url.spec.whatwg.org/#dom-url-hash), although the spec does not seem clear to me if the # will be removed from the URL.

What do you think about this? What is the approach for this case?

**Comment by domenic** [comment]
> I took a look at the WPT tests and I could not find any case that would cover this behavior under [the location interface test cases](https://github.com/web-platform-tests/wpt/tree/master/html/browsers/history/the-location-interface).

I agree. I think you'll need to add a new test, in the to-upstream folder.

> I'm wondering if this is a bug in browsers implementation 🤔.

I don't think so. What leads you to that conclusion?

> . jsdom was implementing the hash setter according to the [URL Living Standard](https://url.spec.whatwg.org/#dom-url-hash), although the spec does not seem clear to me if the # will be removed from the URL.

That's the bug. It should be implementing the spec for the Location object, under "the hash setter steps" at https://html.spec.whatwg.org/#dom-location-hash.

**Pull request closed without merging**
