### PR TITLE
Add README entry about jsdom-devtools-formatter

### PR DESCRIPTION
**Pull request by viddo**
…as suggested by @domenic on the mailing list, https://groups.google.com/d/msg/jsdom/5bZXCNvqZmM/SBkb37V9AAAJ

Let me know if you want it placed somewhere else and/or want it rephrased.

### CODE REVIEW

**Comment by domenic** [comment]
Thanks so much, and sorry for the delay! (I was on vacation.)

**Comment by viddo** [comment]
No worries, hope you had a good vacation! 🙂

**Comment by TimothyGu** [comment]
This is really cool! Thanks for making it.

(And I had no idea that there was a jsdom mailing list.)

Would you be open to the idea of bringing the repo into the umbrella of the jsdom GitHub organization?

**Comment by viddo** [comment]
Yeah, no problem. That would probably help with visibility and
contributions too in the long term. How do one bring the repo other though?

**Comment by viddo** [comment]
Read up on https://help.github.com/articles/about-repository-transfers/

> When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. **If the new owner doesn't accept the transfer within one day, it won't complete.**

So it appears I should be able to do it fine. I could do it whenever this week for example, but someone on your side would have to accept it promptly then. Can you confirm?

**Comment by TimothyGu** [comment]
@viddo Sure!

**Comment by viddo** [comment]
screen shot 2018-04-03 at 21 47 31

Missed [this related help-article](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/) obviously:

> You can transfer a repository owned by your organization to your personal user account **or to another organization where you have repository creation permissions.**

Can you grant me permissions so I can transfer it?

**Pull request merged**
