### PR TITLE
Mock SVGSVGElement methods

### PR DESCRIPTION
**Pull request by m1gu3l**
May help with #2647.
Will allow using [Leaflet ](https://github.com/Leaflet/Leaflet/blob/472407cd2ec8a5f05f0ea0e060c0e41b61778c57/src/core/Browser.js#L143) in jsdom.

### CODE REVIEW

**Comment by domenic** [comment]
It's not clear why this belongs in jsdom. Code that uses jsdom could add these mocks themselves...

**Comment by m1gu3l** [comment]
Of course, but since those methods are part of the living standard I thought it would be nice if jsdom had them. Other libraries (modernizr f.e.) also use those to detect whether environment supports SVG and it may cause not so obvious errors in tests. It's up to you though.

**Comment by domenic** [comment]
Well, but these implementations that you've provided are not part of the SVG standard ;).

**Comment by m1gu3l** [comment]
You're right, those are stubs - but the error would be meaningful.

**Comment by TimothyGu** [comment]
This actually makes it more difficult to feature-detect SVG. Previously one could have done `method in document`, but now they have to use a `try`-`catch` to do that correctly.

**Comment by TimothyGu** [comment]
Actually, I misunderstand – in the case of Leaflet you actually want to have jsdom treated as an SVG-capable user agent. I don't know how Leaflet is using the SVG APIs, but it's dangerous for us to say the functions are available since it's possible that they end up using those mocked functions and weird errors start popping up. Best to leave the decision of mocking or not to the user. :)

**Comment by m1gu3l** [comment]
Leaflet doesn't use those methods, it's just for capability check. But let's say some other lib does. Is it better to get "undefined is not a function" or "createSVGRect is not implemented"?

**Pull request closed without merging**
