### PR TITLE
Add User-Agent header to CORS preflight requests

### LINKED ISSUE #1659: Headers user-agent,... forbidden for GitHub API
I try to use GitHub API from JSDOM. But I always receive error "Headers user-agent, authentication forbidden" when I set required headers. In browers all works fine.

I have explored a source code of XMLHttpReqest (xmlhttprequest.js and xhr-utils.js). I see preflight request to server but result of it is not used for validation of final resquest's result.

For example:

Client side:
```
var xmlhttp = new XMLHttpRequest();
var url = 'http://localhost/';
xmlhttp.open('GET', url, true);
xmlhttp.setRequestHeader('User-Agent', 'test');
xmlhttp.send(null);
```

Server side:
```
var express = require('express')
  , cors = require('cors')
  , app = express();

app.use(cors());

app.get('/', function (req, res) {
  res.send('Hello World!');
});

app.listen(80, function () {
  console.log(`Example app listening on port 80!`);
});

```

Result: ```Error: Headers user-agent forbidden```

As I understand header ```access-control-allow-headers``` must be forworded from preflight request's response (```xhr-utils.js:281```) to real request's response validation (```xmlhttprequest.js:958```).

### PR DESCRIPTION
**Pull request by BehindTheMath**
Fixes #1659

This mirrors the behavior of other browsers, and fixes broken XHR requests to APIs that require a User-Agent header for all requests, such as api.github.com.

### CODE REVIEW

**Comment by domenic** [comment]
It'd be great to fix this, but we'd need a web platform test (maybe one already exists) to ensure this behavior stays around. See https://github.com/tmpvar/jsdom/blob/master/Contributing.md for more details.

**Comment by BehindTheMath** [comment]
I submitted a PR to `web-platform-tests`: https://github.com/w3c/web-platform-tests/pull/10326

**Comment by BehindTheMath** [comment]
@domenic That PR has been merged upstream, so when the submodule is updated, Jsdom will have the tests available.

**Comment by domenic** [comment]
Awesome work, thank you!! I will work on rolling the tests and merging this PR this weekend.

**Comment by BehindTheMath** [comment]
@domenic Is there anything holding this up from being merged?

**Comment by domenic** [comment]
We're waiting on #2197 to finish up, then we should be good to go!

**Pull request merged**
