### PR TITLE
2792 replace request with node fetch

### LINKED ISSUE #2792: Replace request with something better
We are currently using [both](https://github.com/jsdom/jsdom/blob/d240291edbe7d4180a5152993ced7950c834dc57/package.json#L35-L36) request and request-promise-native. We should replace them both with something better.

- **request** is in [maintenance mode](https://github.com/request/request/issues/3142).
- **request** is already quite [bloated](https://bundlephobia.com/result?p=request@2.88.0).
- **request-promise-native** uses [stealthy-require](https://www.npmjs.com/package/stealthy-require) which essentially results in two copies of request (see https://github.com/jsdom/jsdom/pull/2783#issuecomment-572415665)

Some alternatives are in https://github.com/request/request/issues/3143. Strongest candidate right now is probably **[node-fetch](https://www.npmjs.com/package/node-fetch)**.

### PR DESCRIPTION
**Pull request by tobyhinloopen**
Closes #2792

This is a work in progress.

### CODE REVIEW

**Review by gustawdaniel — APPROVED** [review]
Please accept this pull request.

**Comment by gustawdaniel** [comment]
There are problem with linter:

```
$ eslint . --cache --ext .js,.html
/home/travis/build/jsdom/jsdom/lib/jsdom/browser/resources/resource-loader.js
    8:29  error  Strings must use doublequote                                                                                   quotes
   89:12  error  Unnecessary 'else' after 'return'                                                                              no-else-return
  102:21  error  Unexpected trailing comma                                                                                      comma-dangle
  106:29  error  Unexpected parentheses around single function argument                                                         arrow-parens
  106:29  error  'url' is already declared in the upper scope                                                                   no-shadow
  113:11  error  'url' is already declared in the upper scope                                                                   no-shadow
  126:15  error  Use object destructuring                                                                                       prefer-destructuring
  137:12  error  Missing semicolon                                                                                              semi
  143:15  error  Expected a function declaration                                                                                func-style
  143:26  error  'url' is already declared in the upper scope                                                                   no-shadow
  160:15  error  Expected a function declaration                                                                                func-style
  160:30  error  Missing space before function parentheses                                                                      space-before-function-paren
  161:37  error  Unexpected parentheses around single function argument                                                         arrow-parens
  167:25  error  There should be no space after '['                                                                             array-bracket-spacing
  167:36  error  There should be no space before ']'                                                                            array-bracket-spacing
  173:22  error  Unexpected trailing comma                                                                                      comma-dangle
  178:1   error  Expected indentation of 12 spaces but found 10                                                                 indent
  178:18  error  Unexpected parentheses around single function argument                                                         arrow-parens
  179:1   error  Expected indentation of 12 spaces but found 10                                                                 indent
  179:18  error  Unexpected parentheses around single function argument                                                         arrow-parens
  179:18  error  'result' is already declared in the upper scope                                                                no-shadow
  179:26  error  Expected to return a value at the end of arrow function                                                        consistent-return
  179:29  error  Statement inside of curly braces should be on next line                                                        brace-style
  179:31  error  Expected { after 'if' condition                                                                                curly
  179:73  error  Closing curly brace should be on the same line as opening curly brace or on the line after the previous block  brace-style
  180:1   error  Expected indentation of 12 spaces but found 10                                                                 indent
  180:19  error  Unexpected parentheses around single function argument                                                         arrow-parens
  180:26  error  Expected to return a value at the end of arrow function                                                        consistent-return
  181:1   error  Expected indentation of 14 spaces but found 12                                                                 indent
  182:1   error  Expected indentation of 16 spaces but found 14                                                                 indent
  183:1   error  Expected indentation of 18 spaces but found 16                                                                 indent
  184:1   error  Expected indentation of 16 spaces but found 14                                                                 indent
  184:22  error  Unnecessary 'else' after 'return'                                                                              no-else-return
  185:1   error  Expected indentation of 18 spaces but found 16                                                                 indent
  186:1   error  Expected indentation of 16 spaces but found 14                                                                 indent
  187:1   error  Expected indentation of 14 spaces but found 12                                                                 indent
  188:1   error  Expected indentation of 12 spaces but found 10                                                                 indent
  193:11  error  Expected method shorthand                                                                                      object-shorthand
  193:26  error  Missing space before function parentheses                                                                      space-before-function-paren
  199:11  error  Expected method shorthand                                                                                      object-shorthand
  199:26  error  Missing space before function parentheses                                                                      space-before-function-paren
  200:47  error  Missing semicolon                                                                                              semi
/home/travis/build/jsdom/jsdom/test/util.js
  160:12  error  'fetch' is not defined                                  no-undef
  160:65  error  Unexpected parentheses around single function argument  arrow-parens
  166:10  error  Unnecessary 'else' after 'return'                       no-else-return
✖ 45 problems (45 errors, 0 warnings)
  36 errors and 0 warnings potentially fixable with the `--fix` option.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command "yarn lint" exited with 1.
```

Zrzut ekranu z 2020-09-09 08-47-53

https://travis-ci.com/github/jsdom/jsdom/jobs/377612444

**Comment by SagnikPradhan** [comment]
So the only show stopper right now is the eslint formatting?

**Comment by andrewaylett** [comment]
I've fixed the linter problems in #3054 but one of the builds suffered a test failure.  Please feel free to pull the lint fixes into this PR :).

**Comment by BeigeBox** [comment]
> So the only show stopper right now is the eslint formatting?

Do you intend to incorporate the eslint changes into your PR?  That would be super cool if you could, seems the “requests” issue has become a major issue for several platforms now.

**Comment by tobyhinloopen** [comment]
status report here: https://github.com/jsdom/jsdom/issues/2792#issuecomment-739837878

**Pull request closed without merging**
