### PR TITLE
Cleanup xhr timeouts on error

### PR DESCRIPTION
**Pull request by rayvincent2**
Fixes issue #3433 by ensuring that the timeouts are cleared if an error occurs

### CODE REVIEW

**Comment by domenic** [comment]
Thanks, but we cannot accept this change without a test that fails before and passes afterward.

**Comment by rayvincent2** [comment]
Very good.  I'll add a test.  I'm assuming that things look good otherwise?

**Comment by domenic** [comment]
I can't really tell, because without a test I don't know if this fixes the issue :). But assuming it does, yes, this seems simple enough.

**Comment by domenic** [comment]
Closing for now, but if you add a test we'll reopen.

**Pull request closed without merging**
