### PR TITLE
Roll Web Platform Tests

### PR DESCRIPTION
**Pull request by Zirro**
In addition to the regular roll, I've been generous with the timeout status for slow (8+ seconds, mostly) failing tests. I think it's reasonable as most of them are unlikely to start passing without an effort targeted at them specifically.

This roll also seems to fix https://github.com/jsdom/jsdom/issues/1949 🎉, as the `xhr/setrequestheader-allow-empty-value.htm` and `xhr/setrequestheader-allow-whitespace-in-value.htm` started passing. The tests themselves haven't changed, so I suppose this comes down to changes in the WPT tooling.

### CODE REVIEW

**Comment by domenic** [comment]
Can we add a new status, instead of using timeout for things that don't actually timeout? We'd treat it the same, but it would be useful when working on the tests later.

**Comment by domenic** [comment]
Also, I'm confused by the sudden build failures on the to-upstream tests...

**Comment by Zirro** [comment]
> Can we add a new status...

Sure. `fail-slow`?

> Also, I'm confused by the sudden build failures on the to-upstream tests...

I guess the `assert_exists()` method was removed from testharness. I'll look into replacing it.

**Comment by Zirro** [comment]
I've resolved the issues.

**Pull request merged**
