### PR TITLE
Add DocumentFragment.prototype.getElementById

### PR DESCRIPTION
**Pull request by domenic**
Based on a patch by @Zirro from IRC, with my own tests added. However, this does *not* work, because the functions in Element-impl.js that update the `_ids` collection do not care about DocumentFragment containers.

I'm unsure how to proceed. I guess one route is to have totally separate implementations of getElementById for Document and DocumentFragment, with the DocumentFragment version doing a whole traversal. That seems relatively easy. Alternately we could try to develop some kind of caching system, and a notation of "root" i.e. furthest ancestor.

Thoughts welcome.

### CODE REVIEW

**Comment by Sebmaster** [comment]
> I guess one route is to have totally separate implementations of getElementById for Document and DocumentFragment, with the DocumentFragment version doing a whole traversal.

That'd be very okay with me, really. Implement first, speed up later.

However:

> However, this does not work, because the functions in Element-impl.js that update the _ids collection do not care about DocumentFragment containers.

Do we not have the elementAttached thing which we could use for that? Does that bubble to the documentfragment?

**Comment by domenic** [comment]
Hmm, I kind of assumed attached only worked on documents, not document fragments. But I didn't check.

**Comment by dperini** [comment]
@domenic a couple of notes on gEBID implementation... Nodes/Elements attached to a DocumentFragment always have their `isConnected` property set to 'false'. So the `isConnected` thing only works for real Documents (nodeType 9).

Also recall that the HTML5 spec allows for duplicated ID in the same document, thus I believe that would be true also for DocumentFragment (nodeType 11). Does 'jsdom' allow duplicated ID in the same document ?

**Comment by domenic** [comment]
Updated with separate Document and DocumentFragment implementations. It seems to work. Anyone up for reviewing?

I'll try nwsapi on top of this next. BTW @dperini, sorry for not answering your question. Yes, just like in a browser, multiple elements can have the same ID in jsdom.

**Comment by Sebmaster** [comment]
Commit msg has WIP still 😁

**Pull request merged**
