### PR TITLE
fix(canvas): support drawing an empty canvas into other canvas

### PR DESCRIPTION
**Pull request by zjffun**

### CODE REVIEW

**Comment by domenic** [comment]
Thanks! Per the contributing.md, can you add a web platform test, instead of a test in the legacy to-port-to-wpts folder?

**Comment by zjffun** [comment]
All right, I will add.

**Comment by zjffun** [comment]
@dcousens 

Web platform test added.

https://github.com/web-platform-tests/wpt/pull/23091

**Comment by zjffun** [comment]
Remove the test case from to-upstream, because wpt has merged it.

**Pull request merged**
