### PR TITLE
Update Node.js minimum and dependencies

### PR DESCRIPTION
**Pull request by domenic**
Let's see what CI says...

### CODE REVIEW

**Comment by domenic** [comment]
Minimal repro of Node v18 failures:

```js
"use strict";
const { JSDOM } = require(".");

const dom = new JSDOM(``, { runScripts: "outside-only" });
console.log(Object.getOwnPropertyDescriptor(dom.window, "onhashchange"));
dom.window.onhashchange = () => {};
```

this throws

```
TypeError: Cannot redefine property: onhashchange
    at Object.<anonymous> (C:\Users\Domenic\Dropbox\GitHub\jsdom\jsdom\test.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
```

**Comment by domenic** [comment]
Narrowed it down to a specific vm regression, https://github.com/nodejs/node/issues/42962 . Not sure if this is something we can work around...

**Comment by fregante** [comment]
That seems to have been fixed in Node 18.2.0

**Comment by fregante** [comment]
Yesss 🎉 this hopefully unblocks https://github.com/jsdom/jsdom/pull/3347 😁

**Comment by domenic** [comment]
Yep, I plan to slowly make my way through the open PR backlog, mostly over weekends...

**Pull request merged**
