### PR TITLE
Add support for ports in postmessage

### PR DESCRIPTION
**Pull request by martinffx**
I need to be able to transfer a MessageChannel port via postmessage

https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API/Using_channel_messaging

### CODE REVIEW

**Comment by martinffx** [comment]
Is JSDOM not accepting PR's?

**Comment by benogle** [comment]
Is there a chance this will get merged?

**Comment by martinffx** [comment]
@domenic @SimenB any chance of getting this added? Happy to start working on any feedback you may have?

**Comment by domenic** [comment]
This is not a correct implementation. It appears to pass through any object, not just MessagePort objects. And jsdom doesn't implement MessagePort objects, so that would be the first thing to do.

In general, please follow the specifications when adding new code.

**Comment by martinffx** [comment]
Cool, I'll have a look at updating it to only support [Transferable Objects](https://developer.mozilla.org/en-US/docs/Glossary/Transferable_objects)

**Pull request closed without merging**
