### PR TITLE
refactor: Rename `Window.js` to `Window‑impl.js`

### PR DESCRIPTION
**Pull request by ExE-Boss**
Pre‑requisite for&nbsp;#2835.

---

See&nbsp;<https://github.com/jsdom/jsdom/pull/2764> for&nbsp;explanation.

### CODE REVIEW

**Comment by ExE-Boss** [comment]
I’ve now rebased this on top of <https://github.com/jsdom/jsdom/pull/2548>.

**Comment by TimothyGu** [comment]
I'm going to close this as #2835 is not ready yet. I would advise you to fold this into #2835 itself. Please try to get over your phobia of history rewriting tools in Git like rebase and interactive rebase. And also as a final advice, please use the commit message format that everyone else uses (i.e., not conventional commits) to save us some work when merging your PRs.

**Comment by ExE-Boss** [comment]
Actually, #2835 is ready.

**Comment by TimothyGu** [comment]
Well #2835 is still in draft mode…

**Comment by ExE-Boss** [comment]
I’ll undraft it after all its dependencies (including this) are merged.

**Comment by ExE-Boss** [comment]
> Please try to get over your phobia of history rewriting tools in Git like rebase and interactive rebase.

I have learned the hard way to prefer `git merge` and only use squash and merge once a PR is ready when I accidentally FUBAR’d the codebase of <https://github.com/NOVA-Team/NOVA-Core/pull/234> so much that `javac` would crash during compilation and I had to manually re‑create the history in order to roll‑back the changes which broke it in the first place.

Fixing that hot mess took several days.

**Comment by domenic** [comment]
You're not going to be allowed to work on this project if you do not respect its conventions. Please follow @TimothyGu's advice.

**Comment by TimothyGu** [comment]
> I use a modified Angular commit message format, because that’s what I’m used to.

Well, this may sound awfully obviously but, jsdom is not your project, and we don’t particularly care about what you are used to or not. It is [well-known](https://developer.gnome.org/programming-guidelines/stable/c-coding-style.html) across open source and the software engineering world in general that when you contribute to someone else’s project, you follow their rules. Bringing your own style “is disrespectful, like someone tromping into a spotlessly-clean house with muddy shoes.”

As a maintainer, I have a choice to make every time you submit a PR that looks good otherwise: merge it and fix up all of the style things – myself – or just leave the PR be because it would be too much work to merge it. So far I’ve mostly been doing the former, but I’m telling you that it’s getting closer and closer to my limit.

Same with history rewriting. I don’t know how the heck you managed to do that, but I don’t particularly care. Benefits for using `git rebase origin/master` are clear in that it prevents things like https://github.com/jsdom/webidl2js/pull/179#issuecomment-604100366.

All in all, I’m telling you to do these things that are standard practice at jsdom, whether you like it or not. You could choose to not abide by them, but in turn I could choose to not merge them. That’s just how it is.

**Pull request closed without merging**
