### PR TITLE
Updated nwsapi package to resolve security flaw

### PR DESCRIPTION
**Pull request by RailsCod3rFuture**
Review findings below
https://snyk.io/vuln/SNYK-JS-NWSAPI-2841516

### CODE REVIEW

**Review by alexhknowink — APPROVED** [review]
LGTM

**Comment by thisislawatts** [comment]
Thanks for raising the PR @RailsCod3rFuture.

Are there any manual verification I can help out with to help see this PR merged @alexhknowink?

**Comment by RailsCod3rFuture** [comment]
@thisislawatts We need the maintainer of this repository to merge these changes. But, it should be good to go...We had to remove one test, given that it fixes it.

**Comment by RailsCod3rFuture** [comment]
Yes, it should be @CurtisHughes

**Comment by RailsCod3rFuture** [comment]
When will this get merged @domenic ?

**Comment by domenic** [comment]
No plans to merge this. We already use ^2.2.0 in package.json so any new installs will use 2.2.1 by default.

**Comment by RailsCod3rFuture** [comment]
AWS Inspector is picking up ^2.2.0 as a vulnerability. Thats why we must explicitly set it @domenic.

**Comment by RailsCod3rFuture** [comment]
It simply scans the strings in the yarn.lock file, but doesn't know whether or not you're using the latest version. As long as it shows 2.2.0 -- its throwing false positives. @domenic. We have software thats being audited through aws inspector ~

**Comment by domenic** [comment]
Sorry, I am not responsible for AWS Inspector. I suggest you file a bug against that software.

**Pull request closed without merging**
