### PR TITLE
Don't attempt to load canvas-prebuilt

### LINKED ISSUE #2409: jsdom shouldn't try to load canvas-prebuilt
With the release of `canvas` v2.0, `canvas-prebuilt` has been deprecated as `canvas` tries to download the binaries directly. On jsdom 13 support for canvas < 2 was dropped and there will be no more releases of `canvas-prebuilt` on npm. 

Right now jsdom's code searches for both modules if one fails in [`utils.js`](https://github.com/jsdom/jsdom/blob/7e37b5623cc8850d47ec921e965ef9358d3cced2/lib/jsdom/utils.js#L163):

```js
exports.Canvas = null;
["canvas", "canvas-prebuilt"].some(moduleName => {
  try {
    require.resolve(moduleName);
  } catch (e) {
    // ${moduleName} is not installed
    return false;
  }
  exports.Canvas = require(moduleName);
  if (typeof exports.Canvas.createCanvas !== "function") {
    // In browserify, the require will succeed but return an empty object
    exports.Canvas = null;
  }
  return exports.Canvas !== null;
});
```
This could probably be something like (haven't tested it yet):

```js
exports.Canvas = null;

try {
  exports.Canvas = require(moduleName);
  if (typeof exports.Canvas.createCanvas !== "function") {
    // In browserify, the require will succeed but return an empty object
    exports.Canvas = null;
  }
} catch (e) {
  // canvas is not installed
}
```

This is a very minor thing. Happy to do a PR if you want me to.

/CC @zbjornson as he did the work to support canvas 2 in jsdom in https://github.com/jsdom/jsdom/pull/1964

### PR DESCRIPTION
**Pull request by zbjornson**
Fixes #2409

### CODE REVIEW

**Comment by domenic** [comment]
Thanks, but this deletes a lot of important logic, besides just removing the canvas-prebuilt loop iteration. We should keep that logic.

**Comment by zbjornson** [comment]
How so? `exports.Canvas` becomes `null` or the desired object under the same sets of circumstances as far as I can tell...

**Comment by zbjornson** [comment]
Ah I see, https://github.com/jsdom/jsdom/commit/84987d03dd45f5acf56c1a633e41f07fd077a868#diff-b4d2b12fce9c87d002a9a282c86134ae...

**Comment by molant** [comment]
Which are related to #2410 too.


________________________________

**Comment by zbjornson** [comment]
@domenic I restored the original logic. (Feel free to edit the commit if it's faster/easier than commenting.)

**Pull request merged**
