### PR TITLE
ci: use bahmutov/npm-install

### PR DESCRIPTION
**Pull request by ph-fritsche**
That action uses the cache to speed up installations in CI.

### CODE REVIEW

**Comment by domenic** [comment]
Installation is not a very large percentage of our CI time, and I'd rather not give third party actions access to the CI runner unless the gain is large. So I think it's best not to merge this.

**Comment by Sebmaster** [comment]
Maybe we could consider using the github-native cache action like this https://github.com/actions/cache/blob/main/examples.md#node---yarn, maybe including node_modules? However, this currently takes <20s, I'm not sure there's gonna be much to be gained there.

**Comment by ph-fritsche** [comment]
If we don't speed up the CI time, it does in fact not make much of a difference.

Just posted it here to make you aware of this action.

The `lint` and `build-with-browser` checks are fast - 20s install is one third of the runtime.
(With the action I guess it will be ~5s)

The other checks time out. And report possible leaks. So they need to be fixed.

**Comment by domenic** [comment]
Indeed, some point release of Node.js 14 made backward incompatible changes (and Node v15 made more), and someone needs to work on debugging the tests to find the root cause and fixing them. This PR does not do that.

**Pull request closed without merging**
