### PR TITLE
fix: support wildcard for access-control-allow-headers

### PR DESCRIPTION
**Pull request by silviot**
This PR improves on #2867 adding proper formatting. Solves #2408 

The tests fail for this PR on the latest node version [because they're failing on master](https://travis-ci.com/github/silviot/jsdom/builds/199962084).

I would love adding a test for this fix, but it looks like tests come from a different repository, and I'm not familiar at all with this codebase. If needed I can add a test, but I need some pointers about how to do it.

### CODE REVIEW

**Comment by field123** [comment]
Any timeline on getting this merged? Blocking some testing I'm doing with the Firebase Auth Emulator which uses wildcard allow headers.

**Comment by silviot** [comment]
I was able to have this fix in my project using a `postinstall` entry in the `scripts` part of my `package.json`.

@field123 and others might find this gist useful: https://gist.github.com/silviot/4b062421a2bc6e128ffe666873060cda

**Comment by domenic** [comment]
Tests can be added in the https://github.com/jsdom/jsdom/tree/master/test/web-platform-tests/to-upstream directory. https://github.com/jsdom/jsdom/blob/master/test/web-platform-tests/to-upstream/xhr/access-control-preflight-request-header-returns-origin.html is a reasonable example to copy.

**Comment by silviot** [comment]
@domenic Thanks for the pointer! I added a test and rebased against master.

**Pull request merged**
